### ISSUE TITLE
How can I not change the placeholder?

### ISSUE THREAD

**Issue by dengxiaoning** [noppa/text-security#19]
My test is like this

![910A6F0E-6D58-4da3-9465-6A676FCD1047](https://user-images.githubusercontent.com/26786620/117426641-b134ae00-af56-11eb-97f5-8ed8332b6145.png)

I want to display a "please enter password" ，like this

![8E603DFD-65C6-455a-9468-9A4E6A469926](https://user-images.githubusercontent.com/26786620/117427299-7c752680-af57-11eb-88bd-f3cc0d4da5d7.png)

**Comment by noppa** [comment]
Use the [::placeholder](https://css-tricks.com/almanac/selectors/p/placeholder/) (and its platform-specific versions) pseudo selector  to explicitly set the placeholder font to some other font than the text-security font.

```css
.my-password-input::placeholder {
      font-family: sans-serif; /* or whatever font you want here */
}
```
